version: '2'
services:
    shineaccounting-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/shineaccounting/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=shineaccounting
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
